dhatim/cloudpass

package.json

Closes #25
https://greenkeeper.io/

chore(package): update bootprint to version 0.10.0

---

package.json

Closes #41
https://greenkeeper.io/

chore(package): update gh-pages-travis to version 1.0.3

---

package.json

Closes #52
https://greenkeeper.io/

chore(package): update cross-conf-env to version 1.1.1

---

package.json

Closes #88
https://greenkeeper.io/

fix(package): update nodemailer to version 3.1.7

---

package.json

fix(package): update umzug to version 2.0.1

---

package.json

fix(package): update pg to version 7.1.0

---

package.json

fix(package): update health-checkup to version 1.0.14

---

package.json

fix(package): update pem to version 1.12.0

---

package.json

chore(package): update sqlite3 to version 3.1.13

---

package.json

fix(package): update body-parser to version 1.18.2

---

package.json

fix(package): update pem to version 1.12.3

---

package.json

chore(package): update superagent to version 3.8.0

---

package.json

fix(package): update nodemailer to version 4.3.1

---

package.json

chore(package): update dockerode to version 2.5.3

---

package.json

fix(package): update sequelize to version 4.22.5

---

package.json

fix(package): update sequelize to version 4.23.4

---

package.json

fix(package): update sequelize to version 4.28.6

---

package.json

fix(package): update es6-error to version 4.1.1

---

package.json

fix(package): update sequelize to version 4.32.2

---

package.json

fix(package): update sequelize to version 4.32.6

---

package.json

fix(package): update optional-js to version 2.0.0

---

package.json

chore(package): update tar-fs to version 1.16.2

---

package.json

fix(package): update sequelize to version 4.37.10

---

package.json

fix(package): update pg to version 7.4.2

---

package-lock.json
src/api/controllers/directoryController.js
src/api/helpers/accountHelper.js
src/apps/helpers/applyIdSiteMiddleware.js
src/apps/helpers/errorHandler.js
src/apps/sso.js
src/models/DirectoryProvider.js
swagger/swagger.yaml
tests/integration/saml.js

- Enhanced logging
- Make ssoLogoutUrl optional in SSO configuration.

Miscellaneous improvements for SSO

---

src/apps/registration.js

https://www.notion.so/conciliator/Remplacement-des-captcha-5fcad820ed4f4ad08fd1d465ae98ceba

Spam detection on registration

---

migrations/1.10.0-00-idSiteAccountCreation.js
migrations/1.7.0-00-idSiteAccountCreation.js
src/models/IdSite.js

To enable/disable account creation in login page.

Add attribute idSites.accountCreation

---

migrations/1.8.0-00-idSiteOrganizationEdit.js
src/models/IdSite.js
src/models/helpers/accountStoreWrapperMethods.js

https://www.notion.so/conciliator/Cr-ation-de-tenant-Pay-impossible-87482bc61ebe49e4b8c830a2c7b9a057

Add attribute idSites.organizationEdit

---

src/models/index.js

https://www.notion.so/conciliator/Cloudpass-not-retrying-DB-connexion-2ec03a3916ae44b2855d85cc40c28038

Retry query when a connection or deadlock error occurs
